name: PR Cargo Build / Test / Format / Documentation

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  dev:
    name: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - run: rustup update stable && rustup default stable
      - run: rustup component add rustfmt
      - run: make clean
      - run: make fmt-check
      - run: make build
      - run: make test
      - run: make doc