name: Release artifacts from main

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-upload:
    name: Upload release assets
    runs-on: ubuntu-latest
    # S'assurer que la release est bien créée depuis la branche main
    if: github.event.release.target_commitish == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      # Build user manual
        run: make doc
      - name: Build user manual
        run: make doc

      # Upload release binary
      - name: Upload release asset: server binary
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/release/simeis-server
          asset_name: simeis-server
          asset_content_type: application/octet-stream
          token: ${{ secrets.GITHUB_TOKEN }}

      # Upload release manual
      - name: Upload release asset: user manual
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: doc/manuel_utilisateur.pdf
          asset_name: manuel_utilisateur.pdf
          asset_content_type: application/pdf
          token: ${{ secrets.GITHUB_TOKEN }}

      # Upload release swagger.json
      - name: Upload release asset: Swagger JSON
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: doc/swagger.json
          asset_name: swagger.json
          asset_content_type: application/json
          token: ${{ secrets.GITHUB_TOKEN }}

      # Upload release swagger UI
      - name: Upload release asset: Swagger UI
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: doc/swagger-ui.html
          asset_name: swagger-ui.html
          asset_content_type: text/html
          token: ${{ secrets.GITHUB_TOKEN }}
